### ISSUE TITLE
DDA Client API features

### ISSUE THREAD

**Issue by makcedward** [DagsHub/client#236]
I can upload data to DagsHub through python API. Can we use python API to remove files and search files (i.e. glob package) as well?

**Comment by kbolashev** [comment]
Hi Edward! Thanks for checking out the client!

We don't have any API for deleting files on the backend right now, and for client to be able to do that we'll have to do that first.

Searching is an easier task, and it can actually be accomplished right now with `install_hooks()`. You can use the built-in python `glob.glob()` to search and it will work, because `install_hooks()` makes a lot of builtin os functions aware of the DagsHub repo.
Caveat is you need to have the git repository cloned. No need to pull the data with dvc though :)

```python
import glob

from dagshub.streaming import install_hooks
install_hooks(project_root="<path to the repo>")  # no need to specify project_root if cwd is in the repo

print(glob.glob("**/*.jpg", recursive=True))

```
